<?php

namespace Tests\Unit;

use App\Exceptions\DestinationException;
use App\Station;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Cache;
use Tests\TestCase;


class StationTest extends TestCase
{
    function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $database = $this->app->make('db');

        $database->dropCollection('stations');
    }

    /** @test */

    function a_new_destination_can_be_added_to_existing_station()
    {
        $start_station = 'poznań';
        $destination = 'kraków';

        factory(Station::class)->create([
           'name' => 'poznań',
           'destinations' => []
        ]);

        Station::addDestination($start_station, $destination);

        $result = Station::find($start_station);

        $this->assertEquals($start_station, $result->name);
        $this->assertContains($destination, $result->destinations);
    }

    /** @test */

    function when_new_destination_is_added_cache_is_flushed()
    {
        $start_station = 'poznań';
        $destination = 'kraków';

        factory(Station::class)->create([
            'name' => 'poznań',
            'destinations' => []
        ]);

        Cache::shouldReceive('flush')->once();

        Station::addDestination($start_station, $destination);
    }

    /** @test */

    function can_get_all_routes_matrix()
    {
        factory(Station::class)->create([
            'name' => 'poznań',
            'destinations' => ['łódź']
        ]);
        factory(Station::class)->create([
            'name' => 'warszawa',
            'destinations' => ['łódź', ]
        ]);
        factory(Station::class)->create([
            'name' => 'łódź',
            'destinations' => ['poznań', 'warszawa']
        ]);

        $response = Station::getAllRoutesMatrix();

        $expected_result = [
            'poznań' => ['łódź'],
            'warszawa' => ['łódź'],
            'łódź' => ['poznań', 'warszawa']
        ];

        $this->assertEquals(sort($response), sort($expected_result));
    }

    /** @test */

    function all_routes_matrix_is_cached()
    {
        factory(Station::class)->create([
            'name' => 'poznań',
            'destinations' => ['łódź']
        ]);
        factory(Station::class)->create([
            'name' => 'warszawa',
            'destinations' => ['łódź', ]
        ]);
        factory(Station::class)->create([
            'name' => 'łódź',
            'destinations' => ['poznań', 'warszawa']
        ]);

        Station::getAllRoutesMatrix();

        $this->assertTrue(Cache::has('all_routes'));
    }

    /** @test */

    function a_DestinationException_is_thrown_when_given_destination_already_exist()
    {
        $this->expectException(DestinationException::class);

        $start_station = 'poznań';
        $destination = 'kraków';

        factory(Station::class)->create([
            'name' => 'poznań',
            'destinations' => ['kraków']
        ]);

        Station::addDestination($start_station, $destination);
    }

    /** @test */

    function an_Exception_is_thrown_when_given_start_station_does_not_exists()
    {
        $this->expectException(ModelNotFoundException::class);

        $start_station = 'poznań';
        $destination = 'kraków';

        Station::addDestination($start_station, $destination);
    }

}
